# Generated by Django 5.0.6 on 2024-06-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timereport',
            name='time_taken',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timereport',
            name='workspace_id',
            field=models.CharField(max_length=100),
        ),
    ]
